import os
import datetime
from core.db_manager import DBManager


class UploadManager:
    def __init__(self):
        self.db = DBManager()
        self.log_file = "logs/upload_history.log"
        os.makedirs("logs", exist_ok=True)

    def log_status(self, task_title, status, message):
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        entry = f"[{timestamp}] [{status}] {task_title} | {message}\n"
        with open(self.log_file, "a", encoding="utf-8") as f:
            f.write(entry)

    def prepare_package(self):
        task = self.db.collection.find_one({"status": "ready_to_upload"})
        if not task:
            print("📭 No videos ready for upload prep.")
            return

        print(f"📦 Packaging Video: {task['title']}")
        video_path = task.get("final_video_path")

        if not video_path or not os.path.exists(video_path):
            self.log_status(task["title"], "ERROR", "Video file missing")
            return

        folder = os.path.dirname(video_path)
        filename = os.path.basename(video_path).replace(".mp4", "_METADATA.txt")
        meta_path = os.path.join(folder, filename)
        description = task.get("ai_description", "Subscribe for more!")
        hashtags = task.get("ai_hashtags", "#Shorts")
        tags = task.get("ai_tags", "shorts, video")
        source_url = task.get("source_url", "https://news.google.com")
        # 🟢 NEW: Pretty Format with Emojis
        seo_content = f"""
            ===================================================
            🚀 YOUTUBE UPLOAD METADATA
            ===================================================

            📌 TITLE (Optimized for Clicks):
            {task.get('title')}

            📝 DESCRIPTION:
            {description}

            👇 Read the full story here:
            {source_url}

            ---------------------------------------------------
            🔥 HASHTAGS (Copy & Paste):
            {hashtags}

            🏷️ TAGS (For SEO Box):
            {tags}
            ---------------------------------------------------

            🤖 Generated by: Your AI Automation Bot
            📅 Date: {datetime.datetime.now().strftime('%Y-%m-%d')}
        """
        try:
            with open(meta_path, "w", encoding="utf-8") as f:
                f.write(seo_content)

            self.db.collection.update_one(
                {"_id": task["_id"]}, {"$set": {"status": "completed_packaged"}}
            )
            self.log_status(task["title"], "SUCCESS", f"Metadata saved to {filename}")
            print(f"✅ READY TO UPLOAD! Details saved in: {meta_path}")

        except Exception as e:
            self.log_status(task["title"], "FAILED", str(e))


if __name__ == "__main__":
    UploadManager().prepare_package()
